export const pokemonList = [
  {
    id: 1,
    name: "bulbassaur",
    img: "src/assets/imgs/bulbassaur.svg",
    types: ["grass", "poison"],
    hp: 45,
    attack: 25,
    defense: 25,
    speed: 25,
  },
  {
    id: 2,
    name: "raichu",
    img: "src/assets/imgs/raichu.svg",
    types: ["eletric"],
    hp: 60,
    attack: 90,
    defense: 55,
    speed: 110,
  },
  {
    id: 3,
    name: "squirtle",
    img: "src/assets/imgs/squirtle.svg",
    types: ["water"],
    hp: 60,
    attack: 48,
    defense: 65,
    speed: 43,
  },
];
